---

- name: Install Apache and PHP
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache and PHP packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apache2
        - libapache2-mod-php
        - php
        - php-mysql
        - php-cli
        - php-json
        - php-opcache
        - php-mbstring
        - php-gd
        - php-dom
        - php-zip
        - php-curl

    - name: Enable Apache modules
      apache2_module:
        state: present
        name: "{{ item }}"
      loop:
        - rewrite
        - headers
        - expires

    - name: Restart Apache service
      service:
        name: apache2
        state: restarted

- name: Install MariaDB on dbservers
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MariaDB server and client
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mariadb-server
        - mariadb-client

    - name: Secure MariaDB installation
      mysql_user:
        name: root
        password: "{{ mariadb_root_password }}"
        host: all
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock # Adjust if needed
      vars:
        mariadb_root_password: "Ivan9413" # Replace with a strong password

    - name: Start and enable MariaDB service
      service:
        name: mariadb
        state: started
        enabled: yes
- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
